{{ Html::style('assets/css/bootstrap.min.css') }}
{{ Html::style('assets/css/font-awesome.min.css') }}
{{ Html::style('assets/css/animate.css') }}
{{ Html::style('assets/css/font.css') }}
{{ Html::style('assets/css/li-scroller.css') }}
{{ Html::style('assets/css/slick.css') }}
{{ Html::style('assets/css/jquery.fancybox.css') }}
{{ Html::style('assets/css/theme.css') }}
{{ Html::style('assets/css/style.css') }}
